{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "3867c2d8",
   "metadata": {},
   "source": [
    "<p align=\"center\">\n",
    "  <a href=\"https://www.udacity.com/\">\n",
    "    <img src='https://course_report_production.s3.amazonaws.com/rich/rich_files/rich_files/5511/s300/udacity-logo.png' alt=\"Udacity logo\" width = 100px>\n",
    "   </a>\n",
    "</p>\n",
    "<h3 align=\"center\"><a href='https://www.udacity.com/course/data-analyst-nanodegree--nd002'> Udacity Data Analyst Degree </a></h3>\n",
    "<h4 align=\"center\">Project II: Investigate a Dataset</h4>\n",
    "\n",
    "### Table of Contents\n",
    "\n",
    "- [Installation](#installation)\n",
    "- [Project Motivation](#motivation)\n",
    "- [Project Overview](#project_overview)\n",
    "  - [Choose Your Data Set](#cyds)\n",
    "  - [Get Organized](#go)\n",
    "  - [Analyze Your Data](#ad)\n",
    "  - [Share Your Findings](#sf)\n",
    "- [Submission](#sb)\n",
    "- [Results](#results)\n",
    "- [Licensing, Authors, and Acknowledgements](#licensing)\n",
    "\n",
    "\n",
    "## Installation <a name=\"installation\"></a>\n",
    "\n",
    "Working in a Jupyter Notebook on your PC the installing the following packages (libraries) is required is a must. These packages may be installed using conda or pip. They include:\n",
    "- Pandas\n",
    "- Matplotlib\n",
    "- Seaborn\n",
    "\n",
    "## Project Motivation <a name=\"motivation\"></a>\n",
    "\n",
    "This is an Udacity Nanodegree project.With an interest in public health, I chose this dataset because it offers me a first hand experience of handing a data which I believed to be a real-world scenario in examining public health related issues. I was interested to see: </br>\n",
    "- How responsive to appointments accross aga groups\n",
    "- How much did SMS influence patients showing up for appointments\n",
    "\n",
    "## Project Overview <a name=\"project_overview\"></a>\n",
    "You will perform your own data analysis for the final assignment and produce a file to share that details your conclusions. You need to begin by looking at your dataset and considering what inquiries it may be able to address. Then, you should utilize pandas and NumPy to respond to the queries that most interest you, and then produce a report outlining your findings. In order to accomplish this assignment, you are not obliged to employ inferential statistics or machine learning, but you should make it apparent in your communications that your results are preliminary. Since there isn't a single proper solution, this project is indefinitely open-ended.\n",
    "\n",
    "### Step One - Choose Your Data Set <a name=\"cyds\"></a>\n",
    "\n",
    "Click this [link](https://s3.amazonaws.com/video.udacity-data.com/topher/2018/July/5b57919a_data-set-options/data-set-options.pdf) (available in a Google doc [here](https://docs.google.com/document/d/e/2PACX-1vTlVmknRRnfy_4eTrjw5hYGaiQim5ctr9naaRd4V9du2B5bxpd8FEH3KtDgp8qVekw7Cj1GLk1IXdZi/pub?embedded=True)) to open a document with links and information about data sets that you can investigate for this project. You <strong>must</strong> choose one of these datasets to complete the project.\n",
    "\n",
    "### Step Two - Get Organized <a name=\"go\"></a>\n",
    "\n",
    "Eventually you’ll want to submit your project (and share it with friends, family, and employers). Get organized before you begin. We recommend creating a single folder that will eventually contain:\n",
    "<ul>\n",
    "    <li>The <strong>report</strong> communicating your findings</li>\n",
    "    <li>Any <strong>Python code</strong> you wrote as part of your analysis</li>\n",
    "    <li>The <strong>data set</strong> you used (which you will not need to submit)</li>\n",
    "</ul>\n",
    "You may wish to use a Jupyter notebook, in which case you can submit both the code you wrote and the report of your findings in the same document. Otherwise, you will need to submit your report and code separately. If you would like a <strong>notebook template</strong> to help organize your investigation, you can click <a href=\"https://s3.amazonaws.com/video.udacity-data.com/topher/2018/April/5ac7a08a_investigate-a-dataset-template.ipynb/investigate-a-dataset-template.ipynb.zip\">here</a>. Or there may be a page in the project here called Project Workspace: Complete and Submit Project, where you can do all your work and submit the project.\n",
    "\n",
    "### Step Three - Analyze Your Data <a name=\"ad\"></a>\n",
    "\n",
    "Brainstorm some questions you could answer using the data set you chose, then start answering those questions. You can find some questions in the [data set options](https://s3.amazonaws.com/video.udacity-data.com/topher/2018/July/5b57919a_data-set-options/data-set-options.pdf) to help you get started.\n",
    "\n",
    "Try and suggest questions that promote looking at relationships between multiple variables. You should aim to analyze at least one dependent variable and three independent variables in your investigation. Make sure you use NumPy and pandas where they are appropriate!\n",
    "\n",
    "### Step Four - Share Your Findings<a name=\"sf\"></a>\n",
    "\n",
    "Once you have finished analyzing the data, create a report that shares the findings you found most interesting. If you use a Jupyter notebook, share your findings alongside the code you used to perform the analysis. Make sure that your report text is contained in Markdown cells to clearly distinguish your comments and findings from your code work. You should also feel free to use other tools and software to craft your final report, but make sure that you can submit your report as an HTML or PDF file so that it can be opened easily.\n",
    "\n",
    "## Submission <a name=\"sb\"></a>\n",
    "What to include in your submission\n",
    "<ul>\n",
    "   <li>A PDF or HTML file containing your analysis. This file should include:</li>\n",
    "       <ul>\n",
    "        <li>A note specifying which dataset you analyzed</li>\n",
    "        <li>A statement of the question(s) you posed</li>\n",
    "        <li>A description of what you did to investigate those questions</li>\n",
    "        <li>Documentation of any data wrangling you did</li>\n",
    "        <li>Summary statistics and plots communicating your final results</li>\n",
    "       </ul>\n",
    "   <li>Code you used to perform your analysis. If you used a Jupyter notebook, you can submit your .ipynb. Otherwise, you should submit the code separately in .py file(s).</li>\n",
    "   <li>A list of Web sites, books, forums, blog posts, github repositories, etc. that you referred to or used in creating your submission (add N/A if you did not use any such resources).</li>\n",
    "</ul>\n",
    "\n",
    "## Results <a name=\"results\"></a>\n",
    "- I categorized the ages of patients into `pediatric_ group`, `young_group`, `middle_age_group`, and `elderly_group`\n",
    "- Of the 35422 patients that did receive text messages, 25698 patients did not show up for their appointments and 9784 patients did show up for their appointments. Receiving text messages did not influence patients to show up for their appointments.\n",
    "- A great number of patients elderly age group did showed up to appointments.\n",
    "\n",
    "## Licensing, Authors, Acknowledgements<a name=\"licensing\"></a>\n",
    "Must give credit to Kaggle for the data. You can find the Licensing for the data and other descriptive information at the Udacity Webpage."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "479b3f7d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
